apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ecom-web
  name: ecom-web-svc
  namespace: dev
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ecom-web
  type: LoadBalancer
status:
  loadBalancer: {}
