apiVersion: v1
data:
  DB_HOST: mysql-service.dev.svc.cluster.local
  DB_NAME: ecomdb
  FEATURE_DARK_MODE: "false"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"DB_HOST":"mysql-service.dev.svc.cluster.local","DB_NAME":"ecomdb","FEATURE_DARK_MODE":"false"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":null,"name":"app-config","namespace":"gha-helm"}}
  creationTimestamp: "2026-06-09T21:50:58Z"
  name: app-config
  namespace: gha-helm
  resourceVersion: "8633814"
  uid: 6d395bc5-e490-47ba-816f-945de7197ff8
