name: secret example

on:
    workflow_dispatch:

jobs:
    test-secret:
      runs-on: ubuntu-latest

    steps:
      - name: test secret
        run: |
          echo "Masked Secret" 
          echo ${{ secrets.DOCKER_PASSWORD }
          echo "Secret"
          echo ${{ secrets.DOCKER_PASSWORD }} | sed 's/./*/g'